# Dockerfile

FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y default-jre && \
    apt-get clean

WORKDIR /app

# Create models directory inside container
RUN mkdir -p /app/models && chmod 777 /app/models

COPY data_loader.py /app/data_loader.py
COPY model_trainer.py /app/model_trainer.py
COPY model_eval.py /app/model_eval.py
#COPY model_save.py /app/model_save.py
COPY /data/WA_Fn-UseC_-Telco-Customer-Churn.csv /app/data/churn_data.csv
COPY app.py /app/app.py
COPY model_pred.py /app/model_pred.py
#COPY /models/AutoMLchurn_model.model /app/models/AutoMLchurn.model
COPY templates/index.html /app/templates/index.html


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python model_trainer.py

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]

